### ISSUE TITLE
rb-fsevent, rails_development_boost: TypeError (no implicit conversion of Pathname into String)

### ISSUE THREAD

**Issue by mohanklein** [thedarkone/rails-dev-boost#58]
I am using Ruby 2.2.0 and Rails 4.2.3.
When I try to use rails-dev-boost in one of my projects I get the following error:

*TypeError (no implicit conversion of Pathname into String):
  rb-fsevent (0.9.5) lib/rb-fsevent/fsevent.rb:97:in `popen'
  rb-fsevent (0.9.5) lib/rb-fsevent/fsevent.rb:97:in `open_pipe'
  rb-fsevent (0.9.5) lib/rb-fsevent/fsevent.rb:37:in `run'
  rails-dev-boost (0.3.0) lib/rails_development_boost/async/reactor.rb:75:in `start_watcher!'
  rails-dev-boost (0.3.0) lib/rails_development_boost/async/reactor.rb:53:in `block in start!'*

**Comment by thedarkone** [comment]
Hey @mohanklein,

thank you for reporting this and let me know if a709a10  fixes it for you.

```
# Gemfile
group :development do
  gem 'rails-dev-boost', :github => 'thedarkone/rails-dev-boost'
end

# shell
> bundle update --source rails-dev-boost
```

**Comment by mohanklein** [comment]
fixed my problems!
thank you!
